### ISSUE TITLE
Using an expression to generate command

### ISSUE THREAD

**Issue by Compro-Prasad** [radian-software/apheleia#156]
When I do

```emacs-lisp
(setf (alist-get 'black apheleia-formatters) '("/path/to/venv/bin/black" "-"))
```

it works. But I have different projects where I don't want to run black if its not installed in the virtualenv. So, I want to use a function to get the command dynamically per file and disable it where not available:

```emacs-lisp
(defun get-command ()
  (when black-was-found-in-venv
    '("/path/to/venv/bin/black" "-")))

(setf (alist-get 'black apheleia-formatters) 'get-command)
```

Here, `get-command` function will return the command based on virtualenv and nil when executable wasn't found there. What is the best way to accomplish this?

**Comment by raxod502** [comment]
I think you would use something like this:

```elisp
(setf (alist-get 'black apheleia-formatters) ((get-command)))
```

If the value is a symbol then Apheleia assumes it is a function that defines an Elisp-based formatter. You instead want a list to use a regular command formatter. If an element of the list is not a string then it is evaluated to get a string or list of strings. This wasn't documented before; I added documentation in https://github.com/radian-software/apheleia/commit/1bd5f2b8fae2c3d14792feccb021c2dc95299d46.

You could also put the logic in an external shell script and add that to `$PATH`. Then you can invoke it normally from Apheleia.

**Comment by Compro-Prasad** [comment]
I get the following error when I do it:

```
error in process sentinel: apheleia--format-command: Command cannot start with (compro/black)
error in process sentinel: Command cannot start with (compro/black)
```

Code I am using:

```
(defun compro/black ()
  (when-let* ((root (pet-virtualenv-root))
              (executable (concat root "/bin/black"))
              (exists (file-exists-p executable)))
    executable))
(setf (alist-get 'black apheleia-formatters) '((compro/black)))
```

**Comment by raxod502** [comment]
Odd, I don't know why that error is even in there, although I added it. Fixed in the linked commit.

**Comment by Compro-Prasad** [comment]
Thanks that worked. I am currently using:

```emacs-lisp
(defun compro/black ()
  (when-let* ((root (pet-virtualenv-root))
              (executable (concat root "/bin/black"))
              (exists (file-exists-p executable)))
    `(,executable "-")))
(setf (alist-get 'black apheleia-formatters) '((compro/black)))
```

I am going to close this issue but I will ask for another small feature as its not fixed completely yet. I get the following error when black is not installed in the virtualenv:

```
error in process sentinel: Wrong type argument: stringp, nil
```

I think this would be easy to fix. Instead of showing an error, either fail silently or show an information stating that `black` was enabled but function returned `nil`.

**Comment by raxod502** [comment]
Hmmm. I'm not necessarily sure it would be correct to handle the function returning nil. After all, the interface here is that you have `(compro/black)` as one of the arguments in the command line - thus it should return a string. What about returning `"cat"` when there is no formatting to be done? Then it would leave the file as is.

**Comment by Compro-Prasad** [comment]
> What about returning "cat" when there is no formatting to be done? 

Thanks! That does solve the problem.

But don't you think using `cat` is kind of a hack?

If this is okay then documenting this as an option would be a plus.

**Comment by raxod502** [comment]
I think it's reasonable to request a way that a dynamically generated formatter command could signal that no command is to be run. One reasonable way to implement that might be to have a special symbol `noop` that, if present in the command string, would cause the command invocation to be skipped.

Let's track that feature, if desired, in a separate issue.
